jenkins:
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "hudson.util.DoubleLaunchChecker"
  labelAtoms:
  - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  nodeMonitors:
  - "architecture"
  - "clock"
  - diskSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "swapSpace"
  - tmpSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "responseTime"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  systemMessage: "Welcome to My Jenkins"
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
  clouds:
  - docker:
      disabled:
        disabledByChoice: false
        enabledByChoice: true
      dockerApi:
        connectTimeout: 60
        dockerHost:
          credentialsId: "dockerCertificates"
          uri: "tcp://bede-apps.com:2379"
        readTimeout: 60
      name: "local-docker"
      templates:
      - connector:
          ssh:
            sshKeyStrategy:
              manuallyConfiguredSSHKey:
                credentialsId: "jenkins-ssh-agent-key"
                sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
        dockerTemplateBase:
          bindAllPorts: true
          bindPorts: "2223:22"
          cpuPeriod: 0
          cpuQuota: 0
          image: "vault-ssh-agent:0.0.1"
          tty: true
        labelString: "vault-agent"
        name: "vault-agent"
        pullStrategy: PULL_NEVER
        pullTimeout: 300
        remoteFs: "/home/jenkins/agent"
      - connector:
          ssh:
            sshKeyStrategy:
              manuallyConfiguredSSHKey:
                credentialsId: "jenkins-ssh-agent-key"
                sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
        dockerTemplateBase:
          bindAllPorts: true
          bindPorts: "2223:22"
          cpuPeriod: 0
          cpuQuota: 0
          image: "kubernetes-ssh-agent:0.0.1"
          tty: true
        labelString: "kube-agent"
        name: "kube-agent"
        pullStrategy: PULL_NEVER
        pullTimeout: 300
        remoteFs: "/home/jenkins/agent"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
