services:
  jenkins-onprem:
    build:
      context: ../../docker/jenkins
    image: my-jenkins:1.0.0
    container_name: my-jenkins
    networks:
      - dev-network
    ports:
      - 8091:8080
      - 50000:50000

    volumes:
      - ./jenkins:/var/configurations/casc
      - jenkins_home:/var/jenkins_home
      - ${HOME}/self-certificates/docker/ca-certificate.pem:/home/jenkins/certificates/ca.pem:cached
      - ${HOME}/self-certificates/docker/client-certificate.pem:/home/jenkins/certificates/cert.pem:cached
      - ${HOME}/self-certificates/docker/client-key.pem:/home/jenkins/certificates/key.pem:cached

    env_file:
      - ../../env/jenkins-vars.env

    environment:
      CASC_JENKINS_CONFIG: /var/configurations/casc
      VAULT_TOKEN_FILE: /run/secrets/vaultToken
      VAULT_ADDR: http://localhost:8200
      DOCKER_CERT_PATH: /home/jenkins/certificates
      DOCKER_TLS: 1
      DOCKER_TLS_VERIFY: 1

    secrets:
      - vaultToken

    extra_hosts:
      - "bede-apps.com:192.168.15.10"

volumes:
  jenkins_home:

secrets:
  vaultToken:
    file: ../../secrets/vault-token.txt
