include:
  - ./includes/coder-secrets.yaml
  - ./includes/networks.yaml

services:
  dev-env-demo:
    build:
      context: ../docker/demo
    image: dev-env:demo
    container_name: dev-demo-coder
    env_file:
      - ../env/demo-vars.env
    extends:
      file: ./base/docker-compose.yaml
      service: base

    volumes:
      - ${HOME}/MyProjects/corporate/bitbucket/flux-configs/foundation-infrastructure:/home/${USER}/projects/foundation-infrastructure
      - ${HOME}/MyProjects/corporate/bitbucket/flux-configs/cluster-aks-sandbox-nonprod-westus3-02:/home/${USER}/projects/cluster-aks-sandbox-nonprod-westus3-02
      - ${HOME}/MyProjects/corporate/presentations:/home/${USER}/projects/presentations
      # - ${HOME}/MyProjects/personal:/home/${USER}/projects/personal:rw
      # - ${HOME}/MyProjects/self-certificates:/home/${USER}/certificates:rw
      - ${HOME}/MyProjects/tmp:/home/${USER}/projects/tmp:rw
      - ${HOME}/MyProjects/tmp/ssh:/home/${USER}/.ssh:rw
      # - ${HOME}/.colima/default/docker.sock:/var/run/docker.sock
