include:
  - ./includes/coder-secrets.yaml
  - ./includes/networks.yaml
  - ./tools/hashicorp-vault.yaml
  - ./tools/local-artifactory.yaml
  - ./tools/chart-museum.yaml

services:
  dev-env-devops:
    build:
      context: ../docker/devops
    image: dev-env:devops
    container_name: dev-devops-coder
    env_file:
      - ../env/devops-vars.env
    extends:
      file: ./base/docker-compose.yaml
      service: base

    volumes:
      - ${HOME}/MyProjects/corporate:/home/${USER}/projects/corporate:rw
      - ${HOME}/MyProjects/personal:/home/${USER}/projects/personal:rw
      - ${HOME}/.ssh:/home/${USER}/.ssh
      - ${HOME}/MyProjects/self-certificates:/home/${USER}/certificates:rw
      - ${HOME}/MyProjects/tmp:/home/${USER}/projects/tmp:rw
